/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as access from "./access";
export type { access };
export type { Mileage } from "./Mileage";
export * as factories from "./factories";
export type { Ownable } from "./access/Ownable";
export { Ownable__factory } from "./factories/access/Ownable__factory";
export { Mileage__factory } from "./factories/Mileage__factory";
